/**
 * GameProtocol Module
 * 
 * Exports all protocol structures for the Archero sandbox server.
 * 100+ packet types covering all major game systems.
 */

// Binary serialization
export { BinaryReader, BinaryWriter } from "./binary";

// Common types
export {
  type CCommonRespMsg,
  writeCCommonRespMsg,
  createSuccessResponse,
  type CEquipmentItem,
  writeCEquipmentItem,
  createDefaultEquipmentItem,
  type CHeroItem,
  writeCHeroItem,
  createDefaultHero,
  type CRestoreItem,
  writeCRestoreItem,
  createDefaultRestoreItem,
  type CTimestampItem,
  writeCTimestampItem,
  type CBoxAssuranceItem,
  writeCBoxAssuranceItem,
  createDefaultBoxAssurance,
  type STPetInfo,
  writeSTPetInfo,
  type STHeadItem,
  writeSTHeadItem,
  type CArtifact,
  writeCArtifact,
} from "./common";

// Login packets
export {
  type CUserLoginPacket,
  readCUserLoginPacket,
  type CRespUserLoginPacket,
  writeCRespUserLoginPacket,
  createDefaultLoginResponse,
} from "./login";

// Activity packets
export {
  type CActivityCommonData,
  writeCActivityCommonData,
  type CActivityInvestCondition,
  writeCActivityInvestCondition,
  type CActivityInvestData,
  writeCActivityInvestData,
  type CReqActivityCommon,
  readCReqActivityCommon,
  type CReqActivityShip,
  readCReqActivityShip,
  type CReqActivitySuperRoulette,
  readCReqActivitySuperRoulette,
  type CReqActivityContinueGift,
  readCReqActivityContinueGift,
  type CReqActivityDiamondChoice,
  readCReqActivityDiamondChoice,
  type CReqActivityExchange,
  readCReqActivityExchange,
  type CReqActivityInvest,
  readCReqActivityInvest,
  type CRespActivityCommon,
  writeCRespActivityCommon,
  type CActivityShipRelicsGift,
  writeCActivityShipRelicsGift,
  type CRespActivityShip,
  writeCRespActivityShip,
  type CRespActivitySuperRoulette,
  writeCRespActivitySuperRoulette,
  type CRespActivityContinueGift,
  writeCRespActivityContinueGift,
  type CRespActivityInvest,
  writeCRespActivityInvest,
  type STReqActivityGiftTower,
  readSTReqActivityGiftTower,
  type STReqActivityBingo,
  readSTReqActivityBingo,
  type STReqActivityMining,
  readSTReqActivityMining,
  type STReqActivityPiggyBank,
  readSTReqActivityPiggyBank,
  type STCommonQuickBuyData,
  writeSTCommonQuickBuyData,
  type STAutoDeleteActivityItem,
  writeSTAutoDeleteActivityItem,
  type STRespActivityGiftTower,
  writeSTRespActivityGiftTower,
  type STRespActivityPiggyBank,
  writeSTRespActivityPiggyBank,
  createDefaultActivityResponse,
  createDefaultActivityShipResponse,
} from "./activities";

// Battlepass packets
export {
  type CBattlePassExtraRewardConf,
  writeCBattlePassExtraRewardConf,
  type CBattlePassRewardConf,
  writeCBattlePassRewardConf,
  type CReqBattlepassReward,
  readCReqBattlepassReward,
  type CRespBattlepassConf,
  writeCRespBattlepassConf,
  type CRespBattlepassReward,
  writeCRespBattlepassReward,
  type STActivityBattlePassItem,
  writeSTActivityBattlePassItem,
  type STActivityBattlePass,
  writeSTActivityBattlePass,
  createDefaultBattlepassConf,
} from "./battlepass";

// Daily task packets
export {
  type CRewardItem,
  writeCRewardItem,
  type CDailyTaskInfo,
  readCDailyTaskInfo,
  type CWeeklyTaskInfo,
  readCWeeklyTaskInfo,
  type STDailyTaskExtraRewardData,
  writeSTDailyTaskExtraRewardData,
  type CRespDailyTaskInfo,
  writeCRespDailyTaskInfo,
  type CRespWeeklyTaskInfo,
  writeCRespWeeklyTaskInfo,
  type CDailyPlay,
  readCDailyPlay,
  type CRespDailyPlayInfo,
  writeCRespDailyPlayInfo,
  type CReqDailyIapReward,
  readCReqDailyIapReward,
  type CReqWeekIapReward,
  readCReqWeekIapReward,
  type CReqMonthIapReward,
  readCReqMonthIapReward,
  type CRespDailyIapReward,
  writeCRespDailyIapReward,
  type CRespWeekIapReward,
  writeCRespWeekIapReward,
  type CRespMonthIapReward,
  writeCRespMonthIapReward,
  createDefaultDailyTaskInfo,
} from "./daily";

// Equipment packets
export {
  type CReqEquipWear,
  readCReqEquipWear,
  type CReqEquipTotem,
  readCReqEquipTotem,
  type CEquipRefine,
  readCEquipRefine,
  type CRespEquipWear,
  writeCRespEquipWear,
  type CRespEquipTotem,
  writeCRespEquipTotem,
  type CRespEquipRefine,
  writeCRespEquipRefine,
  type CReqHeroSkin,
  readCReqHeroSkin,
  type CHeroSkin,
  writeCHeroSkin,
  type CRespHeroSkin,
  writeCRespHeroSkin,
  type CReqWeaponSkin,
  readCReqWeaponSkin,
  type CRespWeaponSkin,
  writeCRespWeaponSkin,
  type CReqWing,
  readCReqWing,
  type CRespWing,
  writeCRespWing,
  type CReqOpenDragonBox,
  readCReqOpenDragonBox,
  type CRespOpenDragonBox,
  writeCRespOpenDragonBox,
  type CReqOpenPetBox,
  readCReqOpenPetBox,
  type CRespOpenPetBox,
  writeCRespOpenPetBox,
  type CReqOpenEquipSBox,
  readCReqOpenEquipSBox,
  type CRespOpenEquipSBox,
  writeCRespOpenEquipSBox,
} from "./equipment";

// Game packets
export {
  type CGameTowerInfo,
  readCGameTowerInfo,
  type CPlayTowerInfo,
  readCPlayTowerInfo,
  type CRespGameTowerInfo,
  writeCRespGameTowerInfo,
  type CRespPlayTowerInfo,
  writeCRespPlayTowerInfo,
  type CReqGameHarvest2,
  readCReqGameHarvest2,
  type CRespGameHarvest2,
  writeCRespGameHarvest2,
  type CGameAchieveInfo,
  readCGameAchieveInfo,
  type STCommonAchievementData,
  writeSTCommonAchievementData,
  type CRespGameAchieveInfo,
  writeCRespGameAchieveInfo,
  type CGameAd,
  readCGameAd,
  type CRespGameAd,
  writeCRespGameAd,
  type CReqGameGuide,
  readCReqGameGuide,
  type CRespGameGuide,
  writeCRespGameGuide,
  type CReqGameClientData,
  readCReqGameClientData,
  type CRespGameClientData,
  writeCRespGameClientData,
  type CPveSeasonInfo,
  readCPveSeasonInfo,
  type CRespPveSeasonInfo,
  writeCRespPveSeasonInfo,
  type CReqGameFishing,
  readCReqGameFishing,
  type STGameFishingRank,
  writeSTGameFishingRank,
  type CRespGameFishing,
  writeCRespGameFishing,
} from "./game";

// Misc packets (shop, guild, VIP, etc.)
export {
  type CRespShopBoxActivity,
  writeCRespShopBoxActivity,
  type CReqMonthCard,
  readCReqMonthCard,
  type CRespMonthCard,
  writeCRespMonthCard,
  type CReqPrivilegeCard,
  readCReqPrivilegeCard,
  type CRespPrivilegeCard,
  writeCRespPrivilegeCard,
  type STReqVip,
  readSTReqVip,
  type STRespVip,
  writeSTRespVip,
  type CGuildTaskInfo,
  writeCGuildTaskInfo,
  type CRespGuildTaskInfo,
  writeCRespGuildTaskInfo,
  type CGuildAchInfo,
  writeCGuildAchInfo,
  type CRespGuildUserLogin,
  writeCRespGuildUserLogin,
  type CRespQueryGuildRedpacket,
  writeCRespQueryGuildRedpacket,
  type CReqUserBack,
  readCReqUserBack,
  type CRespUserBack,
  writeCRespUserBack,
  type CReqLoginGift,
  readCReqLoginGift,
  type CRespLoginGift,
  writeCRespLoginGift,
  type CReqWeeklyGift,
  readCReqWeeklyGift,
  type CRespWeeklyGift,
  writeCRespWeeklyGift,
  type CReqFirstCharge,
  readCReqFirstCharge,
  type CRespFirstCharge,
  writeCRespFirstCharge,
  type CQueryFirstIAPInfo,
  readCQueryFirstIAPInfo,
  type STReqBindingHabbyID,
  readSTReqBindingHabbyID,
  type STRespBindingHabbyID,
  writeSTRespBindingHabbyID,
  type CReqFarm,
  readCReqFarm,
  type CFarmSlot,
  writeCFarmSlot,
  type CRespFarm,
  writeCRespFarm,
  type CMonsterEgg,
  writeCMonsterEgg,
  type CMonsterHatch,
  writeCMonsterHatch,
  type CRespMonsterHatch,
  writeCRespMonsterHatch,
  type STReqShipBattleSeasonGhostShip,
  readSTReqShipBattleSeasonGhostShip,
  type CShipBattleBaseRank,
  writeCShipBattleBaseRank,
  type STShipBattleSeasonIsLandRankInfo,
  writeSTShipBattleSeasonIsLandRankInfo,
  type STRespShipBattleSeasonGhostShip,
  writeSTRespShipBattleSeasonGhostShip,
  type CDailyGiftGemData,
  writeCDailyGiftGemData,
  type CDailyGiftHeroData,
  writeCDailyGiftHeroData,
  type CReqDailyIapGift,
  readCReqDailyIapGift,
  type CRespDailyIapGift,
  writeCRespDailyIapGift,
} from "./misc";

// Extended activity packets
export * from "./activities_extended";

// ST Activity structures and responses
export * from "./st_activities";
