/**
 * GameProtocol Module
 *
 * Exports all protocol structures for the Archero sandbox server.
 * 100+ packet types covering all major game systems.
 */

// Activity packets
export {
  type CActivityCommonData,
  type CActivityInvestCondition,
  type CActivityInvestData,
  type CActivityShipRelicsGift,
  type CReqActivityCommon,
  type CReqActivityContinueGift,
  type CReqActivityDiamondChoice,
  type CReqActivityExchange,
  type CReqActivityInvest,
  type CReqActivityShip,
  type CReqActivitySuperRoulette,
  type CRespActivityCommon,
  type CRespActivityContinueGift,
  type CRespActivityInvest,
  type CRespActivityShip,
  type CRespActivitySuperRoulette,
  createDefaultActivityResponse,
  createDefaultActivityShipResponse,
  readCReqActivityCommon,
  readCReqActivityContinueGift,
  readCReqActivityDiamondChoice,
  readCReqActivityExchange,
  readCReqActivityInvest,
  readCReqActivityShip,
  readCReqActivitySuperRoulette,
  readSTReqActivityBingo,
  readSTReqActivityGiftTower,
  readSTReqActivityMining,
  readSTReqActivityPiggyBank,
  type STAutoDeleteActivityItem,
  type STCommonQuickBuyData,
  type STReqActivityBingo,
  type STReqActivityGiftTower,
  type STReqActivityMining,
  type STReqActivityPiggyBank,
  type STRespActivityGiftTower,
  type STRespActivityPiggyBank,
  writeCActivityCommonData,
  writeCActivityInvestCondition,
  writeCActivityInvestData,
  writeCActivityShipRelicsGift,
  writeCRespActivityCommon,
  writeCRespActivityContinueGift,
  writeCRespActivityInvest,
  writeCRespActivityShip,
  writeCRespActivitySuperRoulette,
  writeSTAutoDeleteActivityItem,
  writeSTCommonQuickBuyData,
  writeSTRespActivityGiftTower,
  writeSTRespActivityPiggyBank,
} from "./activities";
// Extended activity packets
export * from "./activities_extended";
// Battlepass packets
export {
  type CBattlePassExtraRewardConf,
  type CBattlePassRewardConf,
  type CReqBattlepassReward,
  type CRespBattlepassConf,
  type CRespBattlepassReward,
  createDefaultBattlepassConf,
  readCReqBattlepassReward,
  type STActivityBattlePass,
  type STActivityBattlePassItem,
  writeCBattlePassExtraRewardConf,
  writeCBattlePassRewardConf,
  writeCRespBattlepassConf,
  writeCRespBattlepassReward,
  writeSTActivityBattlePass,
  writeSTActivityBattlePassItem,
} from "./battlepass";
// Binary serialization
export { BinaryReader, BinaryWriter } from "./binary";
// Common types
export {
  type CArtifact,
  type CBoxAssuranceItem,
  type CCommonRespMsg,
  type CEquipmentItem,
  type CHeroItem,
  type CRestoreItem,
  type CTimestampItem,
  createDefaultBoxAssurance,
  createDefaultEquipmentItem,
  createDefaultHero,
  createDefaultRestoreItem,
  createSuccessResponse,
  type STHeadItem,
  type STPetInfo,
  writeCArtifact,
  writeCBoxAssuranceItem,
  writeCCommonRespMsg,
  writeCEquipmentItem,
  writeCHeroItem,
  writeCRestoreItem,
  writeCTimestampItem,
  writeSTHeadItem,
  writeSTPetInfo,
} from "./common";

// Daily task packets
export {
  type CDailyPlay,
  type CDailyTaskInfo,
  type CReqDailyIapReward,
  type CReqMonthIapReward,
  type CReqWeekIapReward,
  type CRespDailyIapReward,
  type CRespDailyPlayInfo,
  type CRespDailyTaskInfo,
  type CRespMonthIapReward,
  type CRespWeekIapReward,
  type CRespWeeklyTaskInfo,
  type CRewardItem,
  type CWeeklyTaskInfo,
  createDefaultDailyTaskInfo,
  readCDailyPlay,
  readCDailyTaskInfo,
  readCReqDailyIapReward,
  readCReqMonthIapReward,
  readCReqWeekIapReward,
  readCWeeklyTaskInfo,
  type STDailyTaskExtraRewardData,
  writeCRespDailyIapReward,
  writeCRespDailyPlayInfo,
  writeCRespDailyTaskInfo,
  writeCRespMonthIapReward,
  writeCRespWeekIapReward,
  writeCRespWeeklyTaskInfo,
  writeCRewardItem,
  writeSTDailyTaskExtraRewardData,
} from "./daily";

// Equipment packets
export {
  type CEquipRefine,
  type CHeroSkin,
  type CReqEquipTotem,
  type CReqEquipWear,
  type CReqHeroSkin,
  type CReqOpenDragonBox,
  type CReqOpenEquipSBox,
  type CReqOpenPetBox,
  type CReqWeaponSkin,
  type CReqWing,
  type CRespEquipRefine,
  type CRespEquipTotem,
  type CRespEquipWear,
  type CRespHeroSkin,
  type CRespOpenDragonBox,
  type CRespOpenEquipSBox,
  type CRespOpenPetBox,
  type CRespWeaponSkin,
  type CRespWing,
  readCEquipRefine,
  readCReqEquipTotem,
  readCReqEquipWear,
  readCReqHeroSkin,
  readCReqOpenDragonBox,
  readCReqOpenEquipSBox,
  readCReqOpenPetBox,
  readCReqWeaponSkin,
  readCReqWing,
  writeCHeroSkin,
  writeCRespEquipRefine,
  writeCRespEquipTotem,
  writeCRespEquipWear,
  writeCRespHeroSkin,
  writeCRespOpenDragonBox,
  writeCRespOpenEquipSBox,
  writeCRespOpenPetBox,
  writeCRespWeaponSkin,
  writeCRespWing,
} from "./equipment";

// Game packets
export {
  type CGameAchieveInfo,
  type CGameAd,
  type CGameTowerInfo,
  type CPlayTowerInfo,
  type CPveSeasonInfo,
  type CReqGameClientData,
  type CReqGameFishing,
  type CReqGameGuide,
  type CReqGameHarvest2,
  type CRespGameAchieveInfo,
  type CRespGameAd,
  type CRespGameClientData,
  type CRespGameFishing,
  type CRespGameGuide,
  type CRespGameHarvest2,
  type CRespGameTowerInfo,
  type CRespPlayTowerInfo,
  type CRespPveSeasonInfo,
  readCGameAchieveInfo,
  readCGameAd,
  readCGameTowerInfo,
  readCPlayTowerInfo,
  readCPveSeasonInfo,
  readCReqGameClientData,
  readCReqGameFishing,
  readCReqGameGuide,
  readCReqGameHarvest2,
  type STCommonAchievementData,
  type STGameFishingRank,
  writeCRespGameAchieveInfo,
  writeCRespGameAd,
  writeCRespGameClientData,
  writeCRespGameFishing,
  writeCRespGameGuide,
  writeCRespGameHarvest2,
  writeCRespGameTowerInfo,
  writeCRespPlayTowerInfo,
  writeCRespPveSeasonInfo,
  writeSTCommonAchievementData,
  writeSTGameFishingRank,
} from "./game";
// Login packets
export {
  type CRespUserLoginPacket,
  type CUserLoginPacket,
  createDefaultLoginResponse,
  readCUserLoginPacket,
  writeCRespUserLoginPacket,
} from "./login";
// Misc packets (shop, guild, VIP, etc.)
export {
  type CDailyGiftGemData,
  type CDailyGiftHeroData,
  type CFarmSlot,
  type CGuildAchInfo,
  type CGuildTaskInfo,
  type CMonsterEgg,
  type CMonsterHatch,
  type CQueryFirstIAPInfo,
  type CReqDailyIapGift,
  type CReqFarm,
  type CReqFirstCharge,
  type CReqLoginGift,
  type CReqMonthCard,
  type CReqPrivilegeCard,
  type CReqUserBack,
  type CReqWeeklyGift,
  type CRespDailyIapGift,
  type CRespFarm,
  type CRespFirstCharge,
  type CRespGuildTaskInfo,
  type CRespGuildUserLogin,
  type CRespLoginGift,
  type CRespMonsterHatch,
  type CRespMonthCard,
  type CRespPrivilegeCard,
  type CRespQueryGuildRedpacket,
  type CRespShopBoxActivity,
  type CRespUserBack,
  type CRespWeeklyGift,
  type CShipBattleBaseRank,
  readCQueryFirstIAPInfo,
  readCReqDailyIapGift,
  readCReqFarm,
  readCReqFirstCharge,
  readCReqLoginGift,
  readCReqMonthCard,
  readCReqPrivilegeCard,
  readCReqUserBack,
  readCReqWeeklyGift,
  readSTReqBindingHabbyID,
  readSTReqShipBattleSeasonGhostShip,
  readSTReqVip,
  type STReqBindingHabbyID,
  type STReqShipBattleSeasonGhostShip,
  type STReqVip,
  type STRespBindingHabbyID,
  type STRespShipBattleSeasonGhostShip,
  type STRespVip,
  type STShipBattleSeasonIsLandRankInfo,
  writeCDailyGiftGemData,
  writeCDailyGiftHeroData,
  writeCFarmSlot,
  writeCGuildAchInfo,
  writeCGuildTaskInfo,
  writeCMonsterEgg,
  writeCMonsterHatch,
  writeCRespDailyIapGift,
  writeCRespFarm,
  writeCRespFirstCharge,
  writeCRespGuildTaskInfo,
  writeCRespGuildUserLogin,
  writeCRespLoginGift,
  writeCRespMonsterHatch,
  writeCRespMonthCard,
  writeCRespPrivilegeCard,
  writeCRespQueryGuildRedpacket,
  writeCRespShopBoxActivity,
  writeCRespUserBack,
  writeCRespWeeklyGift,
  writeCShipBattleBaseRank,
  writeSTRespBindingHabbyID,
  writeSTRespShipBattleSeasonGhostShip,
  writeSTRespVip,
  writeSTShipBattleSeasonIsLandRankInfo,
} from "./misc";

// ST Activity structures and responses
export * from "./st_activities";
