"""
GameProtocol Module

Exports all protocol structures for the Archero server.
Port 12020 binary protocol implementation - Full parity with TypeScript version.
"""

# Binary serialization
from .binary import BinaryReader, BinaryWriter

# Packet framing
from .packet import Packet

# Common types
from .common import (
    CCommonRespMsg,
    CEquipmentItem,
    CHeroItem,
    CRestoreItem,
    CTimestampItem,
    CBoxAssuranceItem,
    STPetInfo,
    STHeadItem,
    CArtifact,
    write_c_common_resp_msg,
    write_c_equipment_item,
    write_c_hero_item,
    write_c_restore_item,
    write_c_timestamp_item,
    write_c_box_assurance_item,
    write_st_pet_info,
    write_st_head_item,
    write_c_artifact,
    create_success_response,
    create_default_equipment_item,
    create_default_hero,
    create_default_restore_item,
    create_default_box_assurance,
)

# Login packets
from .login import (
    CUserLoginPacket,
    CRespUserLoginPacket,
    read_c_user_login_packet,
    write_c_resp_user_login_packet,
    create_default_login_response,
)

# Equipment packets
from .equipment import (
    CReqEquipWear,
    CReqEquipTotem,
    CEquipRefine,
    CRespEquipWear,
    CRespEquipTotem,
    CRespEquipRefine,
    CReqHeroSkin,
    CHeroSkin,
    CRespHeroSkin,
    CReqWeaponSkin,
    CRespWeaponSkin,
    CReqWing,
    CRespWing,
    CReqOpenDragonBox,
    CRespOpenDragonBox,
    CReqOpenPetBox,
    CRespOpenPetBox,
    CReqOpenEquipSBox,
    CRespOpenEquipSBox,
    read_c_req_equip_wear,
    read_c_req_equip_totem,
    read_c_equip_refine,
    read_c_req_hero_skin,
    read_c_req_weapon_skin,
    read_c_req_wing,
    read_c_req_open_dragon_box,
    read_c_req_open_pet_box,
    read_c_req_open_equip_s_box,
    write_c_resp_equip_wear,
    write_c_resp_equip_totem,
    write_c_resp_equip_refine,
    write_c_hero_skin,
    write_c_resp_hero_skin,
    write_c_resp_weapon_skin,
    write_c_resp_wing,
    write_c_resp_open_dragon_box,
    write_c_resp_open_pet_box,
    write_c_resp_open_equip_s_box,
)

# Daily packets
from .daily import (
    CRewardItem,
    CDailyTaskInfo,
    CWeeklyTaskInfo,
    STDailyTaskExtraRewardData,
    CRespDailyTaskInfo,
    CRespWeeklyTaskInfo,
    CDailyPlay,
    CRespDailyPlayInfo,
    CReqDailyIapReward,
    CReqWeekIapReward,
    CReqMonthIapReward,
    CRespDailyIapReward,
    CRespWeekIapReward,
    CRespMonthIapReward,
    read_c_daily_task_info,
    read_c_weekly_task_info,
    read_c_daily_play,
    read_c_req_daily_iap_reward,
    read_c_req_week_iap_reward,
    read_c_req_month_iap_reward,
    write_c_reward_item,
    write_st_daily_task_extra_reward_data,
    write_c_resp_daily_task_info,
    write_c_resp_weekly_task_info,
    write_c_resp_daily_play_info,
    write_c_resp_daily_iap_reward,
    write_c_resp_week_iap_reward,
    write_c_resp_month_iap_reward,
    create_default_daily_task_info,
)

# Battlepass packets
from .battlepass import (
    CBattlePassExtraRewardConf,
    CBattlePassRewardConf,
    CReqBattlepassReward,
    CRespBattlepassConf,
    CRespBattlepassReward,
    STActivityBattlePassItem,
    STActivityBattlePass,
    read_c_req_battlepass_reward,
    write_c_battle_pass_extra_reward_conf,
    write_c_battle_pass_reward_conf,
    write_c_resp_battlepass_conf,
    write_c_resp_battlepass_reward,
    write_st_activity_battle_pass_item,
    write_st_activity_battle_pass,
    create_default_battlepass_conf,
)

# Game packets
from .game import (
    CGameTowerInfo,
    CPlayTowerInfo,
    CRespGameTowerInfo,
    CRespPlayTowerInfo,
    CReqGameHarvest2,
    CRespGameHarvest2,
    CGameAchieveInfo,
    STCommonAchievementData,
    CRespGameAchieveInfo,
    CGameAd,
    CRespGameAd,
    CReqGameGuide,
    CRespGameGuide,
    CReqGameClientData,
    CRespGameClientData,
    CPveSeasonInfo,
    CRespPveSeasonInfo,
    CReqGameFishing,
    STGameFishingRank,
    CRespGameFishing,
    read_c_game_tower_info,
    read_c_play_tower_info,
    read_c_req_game_harvest2,
    read_c_game_achieve_info,
    read_c_game_ad,
    read_c_req_game_guide,
    read_c_req_game_client_data,
    read_c_pve_season_info,
    read_c_req_game_fishing,
    write_c_resp_game_tower_info,
    write_c_resp_play_tower_info,
    write_c_resp_game_harvest2,
    write_st_common_achievement_data,
    write_c_resp_game_achieve_info,
    write_c_resp_game_ad,
    write_c_resp_game_guide,
    write_c_resp_game_client_data,
    write_c_resp_pve_season_info,
    write_st_game_fishing_rank,
    write_c_resp_game_fishing,
)

# Misc packets
from .misc import (
    CRespShopBoxActivity,
    CReqMonthCard,
    CRespMonthCard,
    CReqPrivilegeCard,
    CRespPrivilegeCard,
    STReqVip,
    STRespVip,
    CGuildTaskInfo,
    CRespGuildTaskInfo,
    CGuildAchInfo,
    CRespGuildUserLogin,
    CRespQueryGuildRedpacket,
    CReqUserBack,
    CRespUserBack,
    CReqLoginGift,
    CRespLoginGift,
    CReqWeeklyGift,
    CRespWeeklyGift,
    CReqFirstCharge,
    CRespFirstCharge,
    CQueryFirstIAPInfo,
    STReqBindingHabbyID,
    STRespBindingHabbyID,
    CReqFarm,
    CFarmSlot,
    CRespFarm,
    CMonsterEgg,
    CMonsterHatch,
    CRespMonsterHatch,
    STReqShipBattleSeasonGhostShip,
    CShipBattleBaseRank,
    STShipBattleSeasonIsLandRankInfo,
    STRespShipBattleSeasonGhostShip,
    CDailyGiftGemData,
    CDailyGiftHeroData,
    CReqDailyIapGift,
    CRespDailyIapGift,
    read_c_req_month_card,
    read_c_req_privilege_card,
    read_st_req_vip,
    read_c_req_user_back,
    read_c_req_login_gift,
    read_c_req_weekly_gift,
    read_c_req_first_charge,
    read_c_query_first_iap_info,
    read_st_req_binding_habby_id,
    read_c_req_farm,
    read_st_req_ship_battle_season_ghost_ship,
    read_c_req_daily_iap_gift,
    write_c_resp_shop_box_activity,
    write_c_resp_month_card,
    write_c_resp_privilege_card,
    write_st_resp_vip,
    write_c_guild_task_info,
    write_c_resp_guild_task_info,
    write_c_guild_ach_info,
    write_c_resp_guild_user_login,
    write_c_resp_query_guild_redpacket,
    write_c_resp_user_back,
    write_c_resp_login_gift,
    write_c_resp_weekly_gift,
    write_c_resp_first_charge,
    write_st_resp_binding_habby_id,
    write_c_farm_slot,
    write_c_resp_farm,
    write_c_monster_egg,
    write_c_monster_hatch,
    write_c_resp_monster_hatch,
    write_c_ship_battle_base_rank,
    write_st_ship_battle_season_island_rank_info,
    write_st_resp_ship_battle_season_ghost_ship,
    write_c_daily_gift_gem_data,
    write_c_daily_gift_hero_data,
    write_c_resp_daily_iap_gift,
)

# Activity packets
from .activities import (
    CActivityCommonData,
    CActivityInvestCondition,
    CActivityInvestData,
    CReqActivityCommon,
    CReqActivityShip,
    CReqActivitySuperRoulette,
    CReqActivityContinueGift,
    CReqActivityDiamondChoice,
    CReqActivityExchange,
    CReqActivityInvest,
    CRespActivityCommon,
    CActivityShipRelicsGift,
    CRespActivityShip,
    CRespActivitySuperRoulette,
    CRespActivityContinueGift,
    CRespActivityInvest,
    STReqActivityGiftTower,
    STReqActivityBingo,
    STReqActivityMining,
    STReqActivityPiggyBank,
    STCommonQuickBuyData,
    STRespActivityGiftTower,
    STRespActivityPiggyBank,
    write_c_activity_common_data,
    write_c_activity_invest_condition,
    write_c_activity_invest_data,
    read_c_req_activity_common,
    read_c_req_activity_ship,
    read_c_req_activity_super_roulette,
    read_c_req_activity_continue_gift,
    read_c_req_activity_diamond_choice,
    read_c_req_activity_exchange,
    read_c_req_activity_invest,
    write_c_resp_activity_common,
    write_c_activity_ship_relics_gift,
    write_c_resp_activity_ship,
    write_c_resp_activity_super_roulette,
    write_c_resp_activity_continue_gift,
    write_c_resp_activity_invest,
    read_st_req_activity_gift_tower,
    read_st_req_activity_bingo,
    read_st_req_activity_mining,
    read_st_req_activity_piggy_bank,
    write_st_common_quick_buy_data,
    write_st_resp_activity_gift_tower,
    write_st_resp_activity_piggy_bank,
    create_default_activity_response,
    create_default_activity_ship_response,
)

# Message type constants (from game analysis)
MSG_TYPE_USER_LOGIN = 0x0001
MSG_TYPE_USER_LOGIN_RESP = 0x0002
